services: 
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: thermoroute_backend
    ports: 
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - thermoroute_net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    container_name: thermoroute_db
    env_file:
      - ./backend/.env
    ports: 
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - thermoroute_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d thermoroute_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    container_name: thermoroute_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - thermoroute_net

volumes:
  db_data:

networks:
  thermoroute_net:
