---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thermoroute-secrets
  namespace: thermoroute
spec:
  encryptedData:
    FORTYGUARD_API_KEY: AgBETdiDMTwMOCUs0At+5CN0hjL0Ed5dBCr2i6k9QIfiiJDF1IWZ7CXuo3lLDBjp8yr+yGNHSQ3m8optglXy68fNwLILNtQj7rhM1xH9LzgJwrZiXEw7nPMFAKgrYMp0zXmbKIsZZYhfVzKT9vMDJTh8JvEM0gqo4DiHDm2sUhGJsDGa/Ue4WCBXALUlVBNJvLL4Ij6W9qjNqTi/HWky7ASJByNNgZ16Rm4fzcQuPD4XQm4iL+pxcmiKzc0VqWuodbjSBAsRlFdChL9/M/IPKOosFilfGJgMNyhbG3JnRlrP4pEcAOWOSTtNghueh7lC45ftZCp1AdA39Jv20eBzNjB666cptv0eIZb5/f3WwNw91cMzyBJORKyLMwI4kDuHuec9O6eaY1EmbqYCoLNDlq8g2uiQsrjkflsHxxYuQB6GY1cFrGALEwIJG61Nh82HW4i+1wLYa2tiiYdZGgI8SjRZwTziKmiEf4IRu7FyZ4d532NfIMQ8oBUo5ys869+SrK8ffRZFUx58WjuwJHa0cnCjbnirj3g1FkkGXLgcqFT7SvyPEtek4+BHKG3pfcToI/RZACtlDaHs/10bM3wgCmGOH3TBMrPXZwuZZWyPHKe4+yd54D/UneaVEVMvbtXrmCq2PcBguI/Ah1b00nxN08phOvpLZcoXIIG/SMcPFkL+bRUg3UOl4PfBYj7JdqZN2o40QRK88hw5LEIJfkQ=
    POSTGRES_PASSWORD: AgAPLrgBeY3T4wde5y3N7yCrLt0dlaiOb4fVPf4ODEwUymaKllcdYPdN6IkJUroLFi1meuWD6LRFXVudnqp5b7VQulYdWSbEa13m1wvjnRBwbP9ga/EDYhvZnRK+7TuwhEr9u1IFZ6tA2+G/O3CFWqF9SY0++vsYlxcSYlaE2nGVMAC9ebrvRrbth6HJHZSYt1yhbOEpcNDByH5SE5QNUTzeFdIERCoWE3x10dCDDJ04YMl4w5ZxcAG+kH35MJtLZxyFhlhDL95N8o3VD/GmLUA9x04QfgCZMieaKGuCu6Sf6kezAy/Niu1LMlaSETUCWzDAYuC7qliGmIsgO754p2LOnPip0bLEEawxUH/VkTj/Bd6Pb8cnDoCPt0ThJU65RGZZ8lKmCJKzYG3K321XfyIeTAZbVyWWk4uhxPTo9gpG1bBi3JTJDxeAk7lGfWGimWov1nJqiX3Ae4DNZVgRSho6enkTgqL3O9fh0VSFjOHckOImDJMzS+kZ7UgqaDrPzsgn1mOTpkoC5tKKhPCADN//VrWUYk3WFWhrmS5sOOX3f9VxYs9AatqIByvXyHf3uk6gnjYSLLXm7sxBl7e9GUrG6ep1yDiUo2grUaujKNnO8CM+YXnSf0uajqR4qYiE7oPlGIbFr1z7e3VvztGaCq3tWp+ykKjiAbeVgrUwbDb7uVzDL03qz96rua3lXpdg6mPsOydl2WaGleP7u5E1
  template:
    metadata:
      creationTimestamp: null
      name: thermoroute-secrets
      namespace: thermoroute
