apiVersion: v1 
kind: Service 
metadata:
  name: thermoroute-backend
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: thermoroute-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
