apiVersion: apps/v1
kind: Deployment
metadata:
  name: thermoroute-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: thermoroute-backend

spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: thermoroute-backend

  template: 
    metadata:
      labels: 
        app: thermoroute-backend

    spec:
      containers:
        - name: backend-container
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolice: {{ .Values.backend.image.pullPolicy }}
          ports:
            containerPort: {{ .Values.backend.containerPort }}
          
          env:
            - name: SECRET_KEY
              valueFrom:
                secretRefKey:
                  name: thermoroute-secrets
                  key: SECRET_KEY
              
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: thermoroute-secrets
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: thermoroute-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: thermoroute-secrets
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_HOST
              value: thermoroute-postgres

            - name: POSTGRES_PORT
              value: "5432"

            - name: FORTYGUARD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: thermoroute-secrets
                  key: FORTYGUARD_API_KEY

          resources: 
            {{- toYaml .Values.backend.resources | nindent 12}}
