apiVersion: apps/v1
kind: Deployment
metadata:
  name: thermoroute-frontend
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: thermoroute-frontend

  template:
    metadata:
      labels:
        app: thermoroute-frontend

    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
