apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thermoroute-postgres
  namespace: {{ .Values.namespace }}

spec:
  serviceName: thermoroute-postgres
  replicas: 1

  selector:
    matchLabels:
      app: thermoroute-postgres

  template:
    metadata:
      labels:
        app: thermoroute-postgres

    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP

          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: thermoroute-secrets
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: thermoroute-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: thermoroute-secrets
                  key: POSTGRES_PASSWORD

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
    - metadata:
        name: postgres-data

      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gp2

        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size }}
