name: Backend Build

on:
  workflow_run:
    workflows: ['Backend Test']
    types: 
      - completed
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build and Push backend image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with: 
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Image tags 
        id: meta
        run: |
          SHA="${{ github.event.workflow_run.head_sha }}"
          VERSION="v1.0.${{ github.event.workflow_run.run_number }}"

          echo "sha=$SHA" >> "$GITHUB_OUTPUT"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build and Push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/thermoroute-backend:${{ steps.meta.outputs.sha }}
            ${{ vars.DOCKERHUB_USERNAME }}/thermoroute-backend:${{ steps.meta.outputs.version }}
