name: Backend Build

on:
  workflow_run:
    workflows: ['Backend Test']
    types: 
      - completed
    branches:
      - main
      - dev-branch

permissions:
  contents: write

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build and Push backend image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with: 
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/thermoroute-backend:${{ github.event.workflow_run.head_sha }}
            ${{ vars.DOCKERHUB_USERNAME }}/thermoroute-backend:latest
